apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: env-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-test
  template:
    metadata:
      labels:
        app: env-test
      annotations:
        envHash: {{ .Values.env | toYaml | sha256sum }}
        secretHash: {{ .Values.secrets | toYaml | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: localhost:5000/env-test
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secrets
